// Code generated by marker-generator. DO NOT EDIT.

/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package markers

type KubebuilderMarker struct {
	// Name is the marker's name.
	Name string
	// RequiredFields is the list of required fields for this marker. If this field is not empty, the marker is considered to be unique including with this.
	RequiredFields []string
}

var DefaultMarker = KubebuilderMarker{
	Name: "default",
	RequiredFields: []string{
		"value",
	},
}

var GroupnameMarker = KubebuilderMarker{
	Name: "groupName",
}

var KubebuilderDefaultMarker = KubebuilderMarker{
	Name: "kubebuilder:default",
}

var KubebuilderDeprecatedversionMarker = KubebuilderMarker{
	Name: "kubebuilder:deprecatedversion",
}

var KubebuilderExampleMarker = KubebuilderMarker{
	Name: "kubebuilder:example",
}

var KubebuilderMetadataMarker = KubebuilderMarker{
	Name: "kubebuilder:metadata",
}

var KubebuilderPrintcolumnMarker = KubebuilderMarker{
	Name: "kubebuilder:printcolumn",
	RequiredFields: []string{
		"JSONPath",
		"name",
		"type",
	},
}

var KubebuilderPruningPreserveunknownfieldsMarker = KubebuilderMarker{
	Name: "kubebuilder:pruning:PreserveUnknownFields",
}

var KubebuilderResourceMarker = KubebuilderMarker{
	Name: "kubebuilder:resource",
}

var KubebuilderSelectablefieldMarker = KubebuilderMarker{
	Name: "kubebuilder:selectablefield",
	RequiredFields: []string{
		"JSONPath",
	},
}

var KubebuilderSkipMarker = KubebuilderMarker{
	Name: "kubebuilder:skip",
}

var KubebuilderSkipversionMarker = KubebuilderMarker{
	Name: "kubebuilder:skipversion",
}

var KubebuilderStorageversionMarker = KubebuilderMarker{
	Name: "kubebuilder:storageversion",
}

var KubebuilderSubresourceScaleMarker = KubebuilderMarker{
	Name: "kubebuilder:subresource:scale",
	RequiredFields: []string{
		"specpath",
		"statuspath",
	},
}

var KubebuilderSubresourceStatusMarker = KubebuilderMarker{
	Name: "kubebuilder:subresource:status",
}

var KubebuilderUnservedversionMarker = KubebuilderMarker{
	Name: "kubebuilder:unservedversion",
}

var KubebuilderValidationEmbeddedresourceMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:EmbeddedResource",
}

var KubebuilderValidationEnumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Enum",
}

var KubebuilderValidationExclusivemaximumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:ExclusiveMaximum",
}

var KubebuilderValidationExclusiveminimumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:ExclusiveMinimum",
}

var KubebuilderValidationFormatMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Format",
}

var KubebuilderValidationMaxitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MaxItems",
}

var KubebuilderValidationMaxlengthMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MaxLength",
}

var KubebuilderValidationMaxpropertiesMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MaxProperties",
}

var KubebuilderValidationMaximumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Maximum",
}

var KubebuilderValidationMinitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MinItems",
}

var KubebuilderValidationMinlengthMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MinLength",
}

var KubebuilderValidationMinpropertiesMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MinProperties",
}

var KubebuilderValidationMinimumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Minimum",
}

var KubebuilderValidationMultipleofMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:MultipleOf",
}

var KubebuilderValidationOptionalMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Optional",
}

var KubebuilderValidationPatternMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Pattern",
}

var KubebuilderValidationRequiredMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Required",
}

var KubebuilderValidationSchemalessMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Schemaless",
}

var KubebuilderValidationTypeMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:Type",
}

var KubebuilderValidationUniqueitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:UniqueItems",
}

var KubebuilderValidationXembeddedresourceMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:XEmbeddedResource",
}

var KubebuilderValidationXintorstringMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:XIntOrString",
}

var KubebuilderValidationXpreserveunknownfieldsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:XPreserveUnknownFields",
}

var KubebuilderValidationXvalidationMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:XValidation",
	RequiredFields: []string{
		"rule",
	},
}

var KubebuilderValidationItemsEnumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Enum",
}

var KubebuilderValidationItemsExclusivemaximumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:ExclusiveMaximum",
}

var KubebuilderValidationItemsExclusiveminimumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:ExclusiveMinimum",
}

var KubebuilderValidationItemsFormatMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Format",
}

var KubebuilderValidationItemsMaxitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MaxItems",
}

var KubebuilderValidationItemsMaxlengthMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MaxLength",
}

var KubebuilderValidationItemsMaxpropertiesMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MaxProperties",
}

var KubebuilderValidationItemsMaximumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Maximum",
}

var KubebuilderValidationItemsMinitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MinItems",
}

var KubebuilderValidationItemsMinlengthMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MinLength",
}

var KubebuilderValidationItemsMinpropertiesMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MinProperties",
}

var KubebuilderValidationItemsMinimumMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Minimum",
}

var KubebuilderValidationItemsMultipleofMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:MultipleOf",
}

var KubebuilderValidationItemsPatternMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Pattern",
}

var KubebuilderValidationItemsTypeMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:Type",
}

var KubebuilderValidationItemsUniqueitemsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:UniqueItems",
}

var KubebuilderValidationItemsXembeddedresourceMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:XEmbeddedResource",
}

var KubebuilderValidationItemsXintorstringMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:XIntOrString",
}

var KubebuilderValidationItemsXpreserveunknownfieldsMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:XPreserveUnknownFields",
}

var KubebuilderValidationItemsXvalidationMarker = KubebuilderMarker{
	Name: "kubebuilder:validation:items:XValidation",
	RequiredFields: []string{
		"rule",
	},
}

var ListmapkeyMarker = KubebuilderMarker{
	Name: "listMapKey",
}

var ListtypeMarker = KubebuilderMarker{
	Name: "listType",
}

var MaptypeMarker = KubebuilderMarker{
	Name: "mapType",
}

var NullableMarker = KubebuilderMarker{
	Name: "nullable",
}

var OptionalMarker = KubebuilderMarker{
	Name: "optional",
}

var RequiredMarker = KubebuilderMarker{
	Name: "required",
}

var StructtypeMarker = KubebuilderMarker{
	Name: "structType",
}

var VersionnameMarker = KubebuilderMarker{
	Name: "versionName",
}

var AllDefinitions map[string]KubebuilderMarker = map[string]KubebuilderMarker{
	"default":                                             DefaultMarker,
	"groupName":                                           GroupnameMarker,
	"kubebuilder:default":                                 KubebuilderDefaultMarker,
	"kubebuilder:deprecatedversion":                       KubebuilderDeprecatedversionMarker,
	"kubebuilder:example":                                 KubebuilderExampleMarker,
	"kubebuilder:metadata":                                KubebuilderMetadataMarker,
	"kubebuilder:printcolumn":                             KubebuilderPrintcolumnMarker,
	"kubebuilder:pruning:PreserveUnknownFields":           KubebuilderPruningPreserveunknownfieldsMarker,
	"kubebuilder:resource":                                KubebuilderResourceMarker,
	"kubebuilder:selectablefield":                         KubebuilderSelectablefieldMarker,
	"kubebuilder:skip":                                    KubebuilderSkipMarker,
	"kubebuilder:skipversion":                             KubebuilderSkipversionMarker,
	"kubebuilder:storageversion":                          KubebuilderStorageversionMarker,
	"kubebuilder:subresource:scale":                       KubebuilderSubresourceScaleMarker,
	"kubebuilder:subresource:status":                      KubebuilderSubresourceStatusMarker,
	"kubebuilder:unservedversion":                         KubebuilderUnservedversionMarker,
	"kubebuilder:validation:EmbeddedResource":             KubebuilderValidationEmbeddedresourceMarker,
	"kubebuilder:validation:Enum":                         KubebuilderValidationEnumMarker,
	"kubebuilder:validation:ExclusiveMaximum":             KubebuilderValidationExclusivemaximumMarker,
	"kubebuilder:validation:ExclusiveMinimum":             KubebuilderValidationExclusiveminimumMarker,
	"kubebuilder:validation:Format":                       KubebuilderValidationFormatMarker,
	"kubebuilder:validation:MaxItems":                     KubebuilderValidationMaxitemsMarker,
	"kubebuilder:validation:MaxLength":                    KubebuilderValidationMaxlengthMarker,
	"kubebuilder:validation:MaxProperties":                KubebuilderValidationMaxpropertiesMarker,
	"kubebuilder:validation:Maximum":                      KubebuilderValidationMaximumMarker,
	"kubebuilder:validation:MinItems":                     KubebuilderValidationMinitemsMarker,
	"kubebuilder:validation:MinLength":                    KubebuilderValidationMinlengthMarker,
	"kubebuilder:validation:MinProperties":                KubebuilderValidationMinpropertiesMarker,
	"kubebuilder:validation:Minimum":                      KubebuilderValidationMinimumMarker,
	"kubebuilder:validation:MultipleOf":                   KubebuilderValidationMultipleofMarker,
	"kubebuilder:validation:Optional":                     KubebuilderValidationOptionalMarker,
	"kubebuilder:validation:Pattern":                      KubebuilderValidationPatternMarker,
	"kubebuilder:validation:Required":                     KubebuilderValidationRequiredMarker,
	"kubebuilder:validation:Schemaless":                   KubebuilderValidationSchemalessMarker,
	"kubebuilder:validation:Type":                         KubebuilderValidationTypeMarker,
	"kubebuilder:validation:UniqueItems":                  KubebuilderValidationUniqueitemsMarker,
	"kubebuilder:validation:XEmbeddedResource":            KubebuilderValidationXembeddedresourceMarker,
	"kubebuilder:validation:XIntOrString":                 KubebuilderValidationXintorstringMarker,
	"kubebuilder:validation:XPreserveUnknownFields":       KubebuilderValidationXpreserveunknownfieldsMarker,
	"kubebuilder:validation:XValidation":                  KubebuilderValidationXvalidationMarker,
	"kubebuilder:validation:items:Enum":                   KubebuilderValidationItemsEnumMarker,
	"kubebuilder:validation:items:ExclusiveMaximum":       KubebuilderValidationItemsExclusivemaximumMarker,
	"kubebuilder:validation:items:ExclusiveMinimum":       KubebuilderValidationItemsExclusiveminimumMarker,
	"kubebuilder:validation:items:Format":                 KubebuilderValidationItemsFormatMarker,
	"kubebuilder:validation:items:MaxItems":               KubebuilderValidationItemsMaxitemsMarker,
	"kubebuilder:validation:items:MaxLength":              KubebuilderValidationItemsMaxlengthMarker,
	"kubebuilder:validation:items:MaxProperties":          KubebuilderValidationItemsMaxpropertiesMarker,
	"kubebuilder:validation:items:Maximum":                KubebuilderValidationItemsMaximumMarker,
	"kubebuilder:validation:items:MinItems":               KubebuilderValidationItemsMinitemsMarker,
	"kubebuilder:validation:items:MinLength":              KubebuilderValidationItemsMinlengthMarker,
	"kubebuilder:validation:items:MinProperties":          KubebuilderValidationItemsMinpropertiesMarker,
	"kubebuilder:validation:items:Minimum":                KubebuilderValidationItemsMinimumMarker,
	"kubebuilder:validation:items:MultipleOf":             KubebuilderValidationItemsMultipleofMarker,
	"kubebuilder:validation:items:Pattern":                KubebuilderValidationItemsPatternMarker,
	"kubebuilder:validation:items:Type":                   KubebuilderValidationItemsTypeMarker,
	"kubebuilder:validation:items:UniqueItems":            KubebuilderValidationItemsUniqueitemsMarker,
	"kubebuilder:validation:items:XEmbeddedResource":      KubebuilderValidationItemsXembeddedresourceMarker,
	"kubebuilder:validation:items:XIntOrString":           KubebuilderValidationItemsXintorstringMarker,
	"kubebuilder:validation:items:XPreserveUnknownFields": KubebuilderValidationItemsXpreserveunknownfieldsMarker,
	"kubebuilder:validation:items:XValidation":            KubebuilderValidationItemsXvalidationMarker,
	"listMapKey":  ListmapkeyMarker,
	"listType":    ListtypeMarker,
	"mapType":     MaptypeMarker,
	"nullable":    NullableMarker,
	"optional":    OptionalMarker,
	"required":    RequiredMarker,
	"structType":  StructtypeMarker,
	"versionName": VersionnameMarker,
}
